SET NAMES 'utf8';

insert into media_category (`category_name`, `category_alias`, `num`) VALUES 
('Мультфильмы', 'animation', 1),
('Наше кино', 'our_film', 2),
('Мировое кино', 'world_film', 3),
('Документальное', 'doc_film', 4),
('Юмор', 'humor', 5),
('Увлечения', 'liking', 6),
('Наш Сериал', 'owr_serial', 7),
('Зарубежный Сериал', 'world_serial', 8);

insert into cat_genre (`category_alias`, `title`) VALUES 
('animation', 'наши'),
('animation', 'обучающие'),
('animation', 'зарубежные'),
('animation', 'сериал'),
('our_film', 'боевик'),
('our_film', 'военный'),
('our_film', 'драма'),
('our_film', 'детектив'),
('our_film', 'исторический'),
('our_film', 'катастрофы'),
('our_film', 'комедя'),
('our_film', 'мелодрама'),
('our_film', 'музыкальный'),
('our_film', 'приключения'),
('our_film', 'фантастика'),
('our_film', 'триллер'),
('our_film', 'фэнтези'),
('our_film', 'ужасы'),
('our_film', 'эротика'),
('world_film', 'боевик'),
('world_film', 'военный'),
('world_film', 'драма'),
('world_film', 'детектив'),
('world_film', 'исторический'),
('world_film', 'катастрофы'),
('world_film', 'комедия'),
('world_film', 'мелодрама'),
('world_film', 'музыкальный'),
('world_film', 'приключения'),
('world_film', 'фантастика'),
('world_film', 'триллер'),
('world_film', 'фэнтези'),
('world_film', 'ужасы'),
('world_film', 'эротика'),
('world_film', 'вестерн'),
('doc_film', 'биография'),
('doc_film', 'военный'),
('doc_film', 'история'),
('doc_film', 'искусство'),
('doc_film', 'криминал'),
('doc_film', 'катастрофы'),
('doc_film', 'обучающее'),
('doc_film', 'путешествия'),
('doc_film', 'мистика'),
('doc_film', 'техника'),
('doc_film', 'наука'),
('doc_film', 'фантастика'),
('doc_film', 'природа'),
('doc_film', 'здоровье'),
('humor', 'телешоу'),
('humor', 'скетч-шоу'),
('humor', 'юмористы'),
('liking', 'спорт'),
('liking', 'охота'),
('liking', 'танцы'),
('liking', 'кулинария'),
('liking', 'дом/дача'),
('liking', 'рыбалка'),
('liking', 'обучающее'),
('liking', 'фитнес'),
('liking', 'йога'),
('owr_serial', 'боевик'),
('owr_serial', 'военный'),
('owr_serial', 'драма'),
('owr_serial', 'детектив'),
('owr_serial', 'исторический'),
('owr_serial', 'катастрофы'),
('owr_serial', 'комедия'),
('owr_serial', 'мелодрама'),
('owr_serial', 'музыкальный'),
('owr_serial', 'приключения'),
('owr_serial', 'фантастика'),
('owr_serial', 'триллер'),
('owr_serial', 'фэнтези'),
('owr_serial', 'ужасы'),
('world_serial', 'боевик'),
('world_serial', 'военный'),
('world_serial', 'драма'),
('world_serial', 'детектив'),
('world_serial', 'исторический'),
('world_serial', 'катастрофы'),
('world_serial', 'комедия'),
('world_serial', 'мелодрама'),
('world_serial', 'музыкальный'),
('world_serial', 'приключения'),
('world_serial', 'фантастика'),
('world_serial', 'триллер'),
('world_serial', 'фэнтези'),
('world_serial', 'ужасы');
