<?php
session_start();

ob_start();

include "./common.php";
include "./lib/tasks.php";

$error = '';

moderator_access();

if (@$_GET['archive'] == 1 && @$_GET['id']){
    $id = intval(@$_GET['id']);
    
    $year  = date("Y");
    $month = date("n");
    
    if ($month == 1){
        $month = 12;
        $year--;
    }else{
        $month--;
    }
    
    // video archive

    $archive_id = Mysql::getInstance()
        ->from('tasks_archive')
        ->where(array(
            'month' => $month,
            'year'  => $year
        ))
        ->get()
        ->first('id');
    
    if (empty($archive_id)){
        $archive_id = Mysql::getInstance()->insert('tasks_archive', array(
            'date'  => 'NOW()',
            'year'  => $year,
            'month' => $month
        ));
    }

    Mysql::getInstance()->update('moderator_tasks',
        array(
            'archived'      => $archive_id,
            'archived_time' => 'NOW()'
        ),
        array(
            'archived' => 0,
            'ended'    => 1,
            'to_usr'   => $id
        )
    );
    
    // karaoke archive

    $archive_id = Mysql::getInstance()
        ->from('karaoke_archive')
        ->where(array(
            'month' => $month,
            'year'  => $year
        ))
        ->get()
        ->first('id');

    if (empty($archive_id)){
        $archive_id = Mysql::getInstance()->insert('karaoke_archive', array(
            'date'  => 'NOW()',
            'year'  => $year,
            'month' => $month
        ));
    }

    Mysql::getInstance()->update('karaoke',
        array(
            'archived'      => $archive_id,
            'archived_time' => 'NOW()'
        ),
        array(
            'archived' => 0,
            'status'   => 1,
            'accessed' => 1,
            'done'     => 1
        )
    );

    header("Location: last_closed_tasks.php?id=".$id);
    exit();
}
?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">

body {
    font-family: Arial, Helvetica, sans-serif;
    font-weight: bold;
}
td {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 14px;
    text-decoration: none;
    color: #000000;
}
.list{
    border-width: 1px;
    border-style: solid;
    border-color: #E5E5E5;
}
a{
	color:#0000FF;
	font-weight: bold;
	text-decoration:none;
}
a:link,a:visited {
	color:#5588FF;
	font-weight: bold;
}
a:hover{
	color:#0000FF;
	font-weight: bold;
	text-decoration:underline;
}
a.msgs:hover, a.msgs:visited, a.msgs:link{
	font-family: Arial, Helvetica, sans-serif;
	font-size: 14px;
    color:#000000;
	font-weight: bold;
	text-decoration:none;
}
</style>
<title><?= _('Completed tasks')?></title>
</head>
<body>
<table align="center" border="0" cellpadding="0" cellspacing="0">
<tr>
    <td align="center" valign="middle" width="100%" bgcolor="#88BBFF">
    <font size="5px" color="White"><b>&nbsp;<?= _('Completed tasks')?>&nbsp;</b></font>
    </td>
</tr>
<tr>
    <td width="100%" align="left" valign="bottom">
        <a href="tasks.php"><< <?= _('Back')?></a>
    </td>
</tr>
<tr>
    <td align="center">
    <font color="Red">
    <strong>
    <? echo $error?>
    </strong>
    </font>
    <br>
    <br>
    </td>
</tr>
<tr>
<td>

<table border="0" align="center" width="620">
<tr>
<td>
<font color="Gray">* <?= _('report generated by closed-month movies')?></font>
</td>
</tr>
</table>

</td>
</tr>
</table>
<?

$where = '';

if (check_access(array(1))){
    $uid = @$_GET['id'];
}else{
	if (@$_SESSION['uid'] != @$_GET['id']){
		$uid = 0;
	}else{
		$uid = $_SESSION['uid'];
	}
}
?>
    
    <table border="0" align="center" width="760">
    <tr>
    <td align="center">
    
    <table border="1" width="100%" cellspacing="0">
        <tr>
            <td>#</td>
            <td><?= _('Movie')?></td>
            <td><?= _('Opening date')?></td>
            <td><?= _('Closing date')?></td>
            <td><?= _('Duration, min')?></td>
        </tr>
        <?
        
        $from_time = date("Y-m-d H:i:s",strtotime ("-1 month"));

        $tasks = Mysql::getInstance()
            ->from('moderator_tasks')
            ->where(array(
                'ended'    => 1,
                'rejected' => 0,
                'archived' => 0,
                'to_usr'   => $uid
            ))
            ->orderby('end_time')
            ->get();
        
        $length = 0;
        $total_length = 0;
        $num = 0;

        while($arr = $tasks->next()){

            $num++;
            $length = get_media_length_by_id($arr['media_id']);
            $total_length += $length;
            echo "<tr>";
            echo "<td>$num</td>";
            echo "<td><a href='msgs.php?task={$arr['id']}'>".get_media_name_by_id($arr['media_id'])."</a></td>";
            echo "<td>".$arr['start_time']."</td>";
            echo "<td>".$arr['end_time']."</td>";
            echo "<td align='right'>".$length."</td>";
            echo "</tr>";
        }
        ?>
    </table>
    <table border="0" width="100%">
        <tr>
            <td  width="100%" align="right"> <?= _('Total duration, min')?>:  <b><? echo $total_length?></b></td>
        </tr>
    </table>
    <br>
    <br>
    <center><?= _('Rejected tasks')?></center>
    <table border="1" width="100%" cellspacing="0">
        <tr>
            <td>#</td>
            <td><?= _('Movie')?></td>
            <td><?= _('Opening date')?></td>
            <td><?= _('Closing date')?></td>
            <td><?= _('Duration, min')?></td>
        </tr>
    <?

    $tasks = Mysql::getInstance()
        ->from('moderator_tasks')
        ->where(array(
            'ended'    => 1,
            'rejected' => 1,
            'archived' => 0,
            'to_usr'   => $uid
        ))
        ->get();

    $num = 0;
    while($arr = $tasks->next()){

        $num++;
        $length = get_media_length_by_id($arr['media_id']);
        echo "<tr>";
        echo "<td>$num</td>";
        echo "<td><a href='msgs.php?task={$arr['id']}'>".get_media_name_by_id($arr['media_id'])."</a></td>";
        echo "<td>".$arr['start_time']."</td>";
        echo "<td>".$arr['end_time']."</td>";
        echo "<td align='right'>".$length."</td>";
        echo "</tr>";
    }
    
    ?>
    </table>
    <br>
    <br>
    <table border="0" width="100%">
    <tr>
        <td align="right">
        <?if (check_access(array(1))){?>
        <input type="button" value="<?= _('Move to archive')?>" onclick="if(confirm('<?= _('Move to the archive?')?>')){document.location='last_closed_tasks.php?id=<?echo @$_GET['id']?>&archive=1';}">
        <?}?>
        </td>
    </tr>
    </table>
    <td>
    </tr>
    </table>
